# =========================
# Base
# =========================
FROM node:24 AS base

WORKDIR /app

# Dépendances système (layer stable)
RUN apt-get update && apt-get install -y \
  ca-certificates \
  curl \
  git \
  && rm -rf /var/lib/apt/lists/*


# =========================
# Dependencies
# =========================
FROM base AS deps

# Copier uniquement les manifests
COPY package*.json ./

# Droits avant npm install
RUN chown -R node:node /app

USER node

# Installation dépendances (cache Docker)
RUN npm install


# =========================
# Development
# =========================
FROM base AS dev

# Copier node_modules depuis deps
COPY --from=deps /app/node_modules ./node_modules

# Copier le reste du code
COPY --chown=node:node . .

USER node

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
