FROM node:24

WORKDIR /app

# Installation des dépendances
COPY package*.json ./
RUN npm install

# Code source (monté en volume ensuite)
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
